version: '3.3'
services:
  mongo:
    ports:
      - '27017:27017'
    image: mongo
    networks:
      - example

  back:
    build: ./Back/
    ports:
      - '3200:3200'
    restart: always
    networks:
      - example
    depends_on:
      - mongo

  front:
    build: ./Front/
    ports:
     - '80:80'
    restart: always
    networks:
      - example
    depends_on:
      - back

networks:
  example:
    driver: bridge